### ISSUE TITLE
Maven central?

### ISSUE THREAD

**Issue by briantopping** [ANierbeck/Karaf-Cassandra#1]
Hi Achim! Thanks for all your work on this. :)

Any thoughts about publishing this to central? I suppose there's no reason not to just fork the tasty bits into one's own project, but maybe there would be some value to a focal point for Cassandra in Karaf work. I'd be happy to kick in some of the publishing stuff if it helps.

WDYT?

**Comment by ANierbeck** [comment]
Hi Brian, 

great that you like it :-)
Need to check if I can go and publish this also from my project if not, another Pax project might be interesting again :-D

regards, Achim

**Comment by briantopping** [comment]
Yes you can definitely publish from your project. Have you seen the Sonatype OSSRH? I could set it up for you and transfer ownership, but it's really not hard.

**Comment by ANierbeck** [comment]
Yeah I'll look at it.

Regards, Achim

sent from mobile device
Am 19.09.2015 8:06 vorm. schrieb "Brian Topping" notifications@github.com:

**Comment by ANierbeck** [comment]
Hi, 

opened an issue for it. 
https://issues.sonatype.org/browse/OSSRH-17792
Will provide a release asap

regards, Achim

**Comment by briantopping** [comment]
Cool, thanks!

**Comment by ANierbeck** [comment]
done: 
https://oss.sonatype.org/content/groups/public/de/nierbeck/

**Comment by briantopping** [comment]
Fabulous, thanks! https://oss.sonatype.org/content/repositories/snapshots/de/nierbeck/cassandra/ :)
